<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_l_recover_method</name>
   <tag></tag>
   <elementGuidId>b20f6a89-a653-49ad-a634-25e540135fc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='send_sms:AYjAyxPtdgHoEko1lBAKuDzB8HFazpl0Iso2qmi7U13Zd8LWGqldT2PqY_tIf3_ftdY']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>76d46865-e4e1-4b2a-929b-c7f82d8f7713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>94643397-63b2-4436-9f1a-d6d98d0ffded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>send_sms:AYjAyxPtdgHoEko1lBAKuDzB8HFazpl0Iso2qmi7U13Zd8LWGqldT2PqY_tIf3_ftdY</value>
      <webElementGuid>39a125f5-2d71-4daa-b41e-95dcd8c6965b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>recover_method</value>
      <webElementGuid>7198148c-04a5-4e9e-96f0-82fd11b7f5a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>send_sms:AYjAyxPtdgHoEko1lBAKuDzB8HFazpl0Iso2qmi7U13Zd8LWGqldT2PqY_tIf3_ftdY</value>
      <webElementGuid>a162439d-b1df-4adc-8f43-ce06cc6e56ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uiInputLabelInput uiInputLabelRadio</value>
      <webElementGuid>ade0f1ef-1c51-46e5-9280-8b2343bd6c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;send_sms:AYjAyxPtdgHoEko1lBAKuDzB8HFazpl0Iso2qmi7U13Zd8LWGqldT2PqY_tIf3_ftdY&quot;)</value>
      <webElementGuid>419f10e9-4a2c-4f43-bbac-0a4999d2a1c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='send_sms:AYjAyxPtdgHoEko1lBAKuDzB8HFazpl0Iso2qmi7U13Zd8LWGqldT2PqY_tIf3_ftdY']</value>
      <webElementGuid>6bd84b81-2af4-4988-af35-8e58502b8a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='initiate_interstitial']/div[2]/table/tbody/tr/td/table/tbody/tr[2]/td/label/div/input</value>
      <webElementGuid>e8a333ea-6f08-4151-b050-4b72f000ab56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/label/div/input</value>
      <webElementGuid>f2f29b22-b8d4-4e7e-9081-9a0cbc80f385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'send_sms:AYjAyxPtdgHoEko1lBAKuDzB8HFazpl0Iso2qmi7U13Zd8LWGqldT2PqY_tIf3_ftdY' and @name = 'recover_method']</value>
      <webElementGuid>6550b90f-48f5-453a-9b48-2cd23ef9507e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
