<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_How do you want to receive the code t_77a821</name>
   <tag></tag>
   <elementGuidId>768f78c6-5f76-4d79-bf2b-888419ddae80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='send_email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#send_email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>32ba7c0d-8c36-4b39-b8ac-605e46c2b5ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>bab131b8-39d0-4324-9841-4aaf8855467c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>send_email</value>
      <webElementGuid>3a5d1c97-c8ba-4103-b209-815a3fbd4992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>recover_method</value>
      <webElementGuid>4d64df9f-3a83-47f7-8b3c-e4870af81222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>send_email</value>
      <webElementGuid>3f4acae2-077d-448b-a758-0f6cc118f1e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f9bda486-d448-4521-87ea-02d5942da04f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uiInputLabelInput uiInputLabelRadio</value>
      <webElementGuid>cce00b49-473c-4301-9b66-8414069423e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;send_email&quot;)</value>
      <webElementGuid>fc80c0d4-2338-4e62-b8e6-8770df2b3c1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='send_email']</value>
      <webElementGuid>b697b5b5-8c44-4eff-abba-8d03813514b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='initiate_interstitial']/div[2]/table/tbody/tr/td/table/tbody/tr/td/label/div/input</value>
      <webElementGuid>fd839953-d26b-4243-b950-29e5972f6738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>dd6e1c7a-b6a4-4a59-97be-713266bdfa69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'send_email' and @name = 'recover_method' and @checked = '1']</value>
      <webElementGuid>89f8d530-755c-445b-a9e1-444f04e483e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
